name: kami

site:
  favicon: /favicon.svg
  # 开屏图 svg 标签，注意 XSS
  logo_svg: null
  # 随机图片
  figure: null

  # 副标题
  subtitle: null

  background:
    src:
      light: /assets/background.png
      dark: /assets/background-night.png
    position: top center fixed

  header:
    menu:
      - title: 源
        path: /
        type: Home
        icon: faDotCircle
        subMenu: []
      - title: 文
        path: /posts
        type: Post
        subMenu: []
        icon: faGlasses
      - title: 记
        type: Note
        path: /notes/latest
        icon: faFeatherAlt
      - title: 言
        path: /says
        icon: faComments
      - title: 览
        icon: faHistory
        path: /timeline
        subMenu:
          - title: 生活
            icon: faFeatherAlt
            path: /timeline?type=note
          - title: 博文
            icon: faBookOpen
            path: /timeline?type=post
          - title: 回忆
            icon: faCircle
            path: /timeline?memory=1
      - title: 友
        icon: faUserFriends
        path: /friends
      - title: 诉
        icon: faComment
        path: /recently
      - title: 余
        icon: faCircleNotch
        path: /favorite/music
        subMenu:
          - title: 听歌
            icon: faMusic
            type: Music
            path: /favorite/music
          - title: 项目
            icon: faFlask
            path: /projects
      - title: ''
        icon: faSubway
        path: 'https://travellings.link'
  social: []

  footer:
    background:
      src:
        dark: ''
        light: /assets/footer.png
      position: top/cover
    home_page: /
    motto:
      content: Stay hungry. Stay foolish.
      author: Steve Jobs
    icp:
      enable: false
      label: '萌备 20201212 号'
      link: https://icp.gov.moe/

    navigation:
      - name: 关于
        path: '/about'
      - name: 留言
        path: '/message'
      - name: 友链
        path: '/friends'
      - name: RSS 订阅
        path: '/feed'
        newtab: true
      - name: 站点地图
        path: '/sitemap'
        newtab: true
      - name: 开往
        path: https://travellings.link/
        newtab: true

  custom:
    script: ''
    style: ''
    js: []
    css: []

page:
  home:
    sections:
      - post
      - note
      - friend
      - more
    title_mapping:
      post: ''
      note: ''
      friend: ''
      more: ''
    more:
      - name: 点赞
        type: 'like'
        cover:
      - name: 订阅
        type: 'subscribe'
        cover:

function:
  comment:
    disable: false
  player:
    # 默认播放列表
    # 只支持网易云
    id:
      - 563534789
      - 1447327083
      - 1450252250
  analyze:
    enable: false
    ga: ''
    baidu: ''
    umami:
      id: ''
      url: ''
      jsname: 'umami'
      # 这是我魔改版本 umami 专属
      endpoint: 'collect'
      hostUrl: '/'
  donate:
    enable: false
    link: https://afdian.net/@example
    qrcode: []

  ban_devtool:
    enable: false

  notification: {}
